chore(all): add chip-set to all.js file
material-components/material-web pull request #5114
Opened 2023-10-24 15:01 UTC by vdegenne

This PR will add `chip-set` element to the list in `all.js`.

2023-10-24 17:35 UTC, asyncLiz requested changes
LGTM, can you add it to `common.js` as well?

2023-10-24 18:53 UTC, asyncLiz approved these changes

2023-10-24 20:35 UTC, AndrewJakubowicz commented
Thank you! Quick nit: internally lint is failing because those imports need to be in alphabetical order.

So `chip-set` needs to be moved down one line between `assist-chip` and `filter-chip`.

2023-10-25 07:08 UTC, vdegenne commented
> Thank you! Quick nit: internally lint is failing because those imports need to be in alphabetical order.
> 
> So `chip-set` needs to be moved down one line between `assist-chip` and `filter-chip`.

I knew there were something with these lint comments 😹
I've updated.

2023-10-25 18:14 UTC, merged