fix(iconbutton): handle activation click
material-components/material-web pull request #5533
Opened 2024-03-18 11:36 UTC by vdegenne

fixes https://github.com/material-components/material-web/issues/5532

2024-03-18 11:38 UTC, vdegenne commented
@asyncLiz I followed the same idea as `<md-text-button>`, however to be totally honest I don't know if that's good or not. Requesting your review.

2024-03-18 20:58 UTC, asyncLiz commented
The form label activation is used to make `<label>` work with some wrapped elements like `<input>`. I think it's fixing the issue as a side effect by forwarding clicks.

Can we try overriding the click method instead? I think it makes more sense to forward the initial click to the delegated element, rather than trigger a host click which re-triggers a button click.

```ts
override click() {
  this.buttonElement?.click();
}
```

If it's more complicated then I'm open to the current approach, but I want to add some documentation to explain what's going on.

2024-03-18 21:00 UTC, asyncLiz requested changes

2024-03-18 21:00 UTC, asyncLiz commented on iconbutton/internal/icon-button.ts
> +  @query('.link') private readonly linkElement!: HTMLElement | null;
Update this to capture both the button and anchor element that could be rendered. Both can have clicks forwarded to them.

```ts
@query('.icon-button') private readonly buttonElement!: HTMLElement | null;
```

2025-08-28 13:19 UTC, closed without merging

2025-08-28 13:19 UTC, vdegenne commented
@asyncliz following https://github.com/material-components/material-web/pull/5843