Convert all doc images to webp
material-components/material-web pull request #5569
Opened 2024-04-06 19:06 UTC by VandeurenGlenn

2024-04-10 16:48 UTC, asyncLiz commented on docs/images/material-web.gif
What changed in this gif?

2024-04-10 16:51 UTC, asyncLiz requested changes
Can you post the settings you used to generate the webp files in the PR's description?

2024-04-10 16:51 UTC, asyncLiz commented on docs/components/images/icon/hero.gif
Same question here as to what changed in the .gif file

2024-04-11 07:08 UTC, VandeurenGlenn commented on docs/images/material-web.gif
Just putted some compression on it.

2024-04-11 07:09 UTC, VandeurenGlenn commented on docs/components/images/icon/hero.gif
This one has some compression also (around 10%) and 10 of the colors (if I remember correctly).

2024-05-07 17:27 UTC, asyncLiz approved these changes
LGTM, sorry for the delay

2024-05-08 17:03 UTC, VandeurenGlenn commented
> LGTM, sorry for the delay

No worries, when ya busy ya busy ;)

2024-05-09 16:39 UTC, asyncLiz requested changes
It looks like `docs/components/images/progress/hero.webp` isn't playing anymore, could you take a look?

2024-05-20 14:52 UTC, VandeurenGlenn commented
> It looks like `docs/components/images/progress/hero.webp` isn't playing anymore, could you take a look?

Oeps, maybe I missed that one and is a gif, I'll see what went wrong.

2024-05-20 15:11 UTC, VandeurenGlenn commented
So it seems animated webp exists, I didn't know, converted that one back to original one, if that one needs to be smaller also it would be best to have the input files because the animations have different frame times.

2024-05-20 17:06 UTC, asyncLiz approved these changes

2024-05-20 20:45 UTC, merged